"""Pro Downloader UI teması — Midnight Ocean."""

# ─── Renkler ───────────────────────────────────────────
BG_PRIMARY = "#0f1923"
BG_SECONDARY = "#1a2736"
BG_TERTIARY = "#243447"
BG_ELEVATED = "#2d3e50"
BG_INPUT = "#162232"

ACCENT_BLUE = "#3b82f6"
ACCENT_BLUE_HOVER = "#2563eb"
ACCENT_GREEN = "#10b981"
ACCENT_GREEN_HOVER = "#059669"
ACCENT_ORANGE = "#f59e0b"
ACCENT_ORANGE_HOVER = "#d97706"
ACCENT_RED = "#ef4444"
ACCENT_RED_HOVER = "#dc2626"
ACCENT_PURPLE = "#8b5cf6"

TEXT_PRIMARY = "#e2e8f0"
TEXT_SECONDARY = "#94a3b8"
TEXT_MUTED = "#64748b"
TEXT_ACCENT = "#60a5fa"

BORDER_DEFAULT = "#1e3a5f"
BORDER_HOVER = "#3b82f6"
BORDER_SUBTLE = "#1a2f45"

# ─── Eski Değişken İsimleri (Geriye Uyum) ──────────────
COLOR_BG = BG_PRIMARY
COLOR_BG_PRIMARY = BG_PRIMARY
COLOR_BG_SECONDARY = BG_SECONDARY
COLOR_BG_TERTIARY = BG_TERTIARY
COLOR_TEXT = TEXT_PRIMARY
COLOR_TEXT_PRIMARY = TEXT_PRIMARY
COLOR_TEXT_MUTED = TEXT_SECONDARY
COLOR_ACCENT = ACCENT_BLUE
COLOR_ACCENT_HOVER = ACCENT_BLUE_HOVER
COLOR_SUCCESS = ACCENT_GREEN
COLOR_WARNING = ACCENT_ORANGE
COLOR_ERROR = ACCENT_RED

# ─── Font ──────────────────────────────────────────────
FONT_FAMILY = "Segoe UI"
FONT_FAMILY_MONO = "Cascadia Code"

FONT_TITLE = (FONT_FAMILY, 20, "bold")
FONT_SUBTITLE = (FONT_FAMILY, 14, "bold")
FONT_BODY = (FONT_FAMILY, 12)
FONT_BODY_BOLD = (FONT_FAMILY, 12, "bold")
FONT_SMALL = (FONT_FAMILY, 10)
FONT_TINY = (FONT_FAMILY, 9)
FONT_MONO = (FONT_FAMILY_MONO, 11)

# ─── Boyutlar ──────────────────────────────────────────
CORNER_RADIUS = 8
CORNER_RADIUS_SMALL = 4
CORNER_RADIUS_LARGE = 12

SIDEBAR_WIDTH = 200
STATUS_BAR_HEIGHT = 32
TAB_HEIGHT = 40

WINDOW_DEFAULT_WIDTH = 1100
WINDOW_DEFAULT_HEIGHT = 700
WINDOW_MIN_WIDTH = 900
WINDOW_MIN_HEIGHT = 600

PADDING_SMALL = 4
PADDING_MEDIUM = 8
PADDING_LARGE = 16
PADDING_XL = 24

# ─── Animasyon ─────────────────────────────────────────
ANIMATION_DURATION_MS = 200
HOVER_TRANSITION_MS = 150
